name: MOVE
seed: 123456
data_cfg:
  user_config: data.yaml
  na_value: NA
  raw_data_path: data/
  interim_data_path: interim_data/
  processed_data_path: processed_data/
  headers_path: headers/
  version: v1
  ids_file_name: baseline_ids.txt
  ids_has_header: true
  ids_colname: 0
  categorical_inputs:
  - name: diabetes_genotypes
    weight: 1
  - name: baseline_drugs
    weight: 1
  - name: baseline_categorical
    weight: 1
  continuous_inputs:
  - name: baseline_continuous
    weight: 2
  - name: baseline_transcriptomics
    weight: 1
  - name: baseline_diet_wearables
    weight: 1
  - name: baseline_proteomic_antibodies
    weight: 1
  - name: baseline_target_metabolomics
    weight: 1
  - name: baseline_untarget_metabolomics
    weight: 1
  - name: baseline_metagenomics
    weight: 1
  data_of_interest: baseline_drugs
  categorical_names: ${names:${data_cfg.categorical_inputs}}
  continuous_names: ${names:${data_cfg.continuous_inputs}}
  categorical_weights: ${weights:${data_cfg.categorical_inputs}}
  continuous_weights: ${weights:${data_cfg.continuous_inputs}}
  data_features_to_visualize_notebook4:
  - drug_1
  - clinical_continuous_2
  - clinical_continuous_3
  write_omics_results_notebook5:
  - baseline_target_metabolomics
  - baseline_untarget_metabolomics
model_cfg:
  _target_: move.models.vae.VAE
  user_config: model.yaml
  seed: 1
  cuda: false
  lrate: 0.0001
  num_epochs: 500
  patience: 100
  kld_steps:
  - 20
  - 30
  - 40
  - 90
  batch_steps:
  - 50
  - 100
  - 150
  - 200
  - 250
  - 300
  - 350
  - 400
  - 450
reconstruction_cfg:
  user_config: tuning_reconstruction.yaml
  num_hidden:
  - 500
  - 1000
  num_latent:
  - 20
  - 50
  num_layers:
  - 1
  - 2
  dropout:
  - 0.1
  - 0.2
  beta:
  - 1.0e-05
  - 0.0001
  batch_sizes:
  - 10
  repeats: 1
  max_param_combos_to_save: 12
stability_cfg:
  user_config: tuning_stability.yaml
  num_hidden:
  - 500
  - 1000
  num_latent:
  - 20
  - 50
  num_layers:
  - 1
  dropout:
  - 0.1
  - 0.2
  beta:
  - 1.0e-05
  batch_sizes:
  - 10
  repeats: 5
  tuned_num_epochs: 250
latent_cfg:
  user_config: training_latent.yaml
  num_hidden: 500
  num_latent: 20
  num_layers: 1
  dropout: 0.1
  beta: 1.0e-05
  batch_sizes: 10
  tuned_num_epochs: 250
association_cfg:
  user_config: training_association.yaml
  num_hidden: 500
  num_latent:
  - 150
  - 200
  - 250
  - 300
  num_layers: 1
  dropout: 0.1
  beta: 1.0e-05
  batch_sizes: 10
  repeats: 10
  tuned_num_epochs: 250
