
defaults:
  - identify_associations_bayes

batch_size: 50

num_refits: 40

target_dataset: random.small.drugs
target_value: 1

model:
  num_hidden:
    - 1000
  num_latent: 200

training_loop:
  lr: 1e-4
  num_epochs: 40
