
defaults:
  - identify_associations_bayes

batch_size: 10

num_refits: 40 # default is 40

target_dataset: random.small.metagenomics
target_value: maximum
save_refits: True

model:
  num_hidden:
    - 1000
  num_latent: 150

training_loop:
  lr: 1e-4
  num_epochs: 40
