
defaults:
  - identify_associations_ks_schema

batch_size: 10

num_refits: 3 # default is 40
sig_threshold: 0.05

target_dataset: random.continuous_basic.proteomics #treatment_level_combined_l1k_train
target_value: plus_std
save_refits: True

model:
  categorical_weights: ${weights:${data.categorical_inputs}}
  continuous_weights: ${weights:${data.continuous_inputs}}
  num_hidden:
    - 12
    #- 560
    #- 250 
    #- 600
  num_latent: 8 
  beta: 0.1
  dropout: 0.1
  cuda: false

training_loop:
  lr: 1e-4
  num_epochs: 200
  batch_dilation_steps:
    - 50
    - 100
    - 150
  kld_warmup_steps:
    - 15
    - 20
    - 25
  early_stopping: false
  patience: 0

perturbed_feature_names:
  - proteomics_3
target_feature_names:
  - metagenomics_9