
defaults:
  - identify_associations_ttest

batch_size: 10

num_refits: 10

target_dataset: random.small.drugs
target_value: 1

model:
  num_hidden:
    - 1000

training_loop:
  lr: 1e-4
  num_epochs: 40
