defaults:
  - identify_associations_ttest

batch_size: 10

num_refits: 2 # default is 40

target_dataset: random.continuous.proteomics #treatment_level_combined_l1k_train
target_value: plus_std
save_refits: True

num_latent:
  - 150
  - 100
  - 75
  - 50

model:
  num_hidden:
    - 200 #600

training_loop:
  lr: 1e-4
  num_epochs: 100 #50