
defaults:
  - identify_associations_bayes

batch_size: 10

num_refits: 2 # default is 40

target_dataset: random.continuous_basic.proteomics #treatment_level_combined_l1k_train
target_value: plus_std
save_refits: True

model:
  num_hidden:
    - 8
    #- 560
    #- 250 
    #- 600
  num_latent: 3 

training_loop:
  lr: 1e-4
  num_epochs: 150
