defaults:
  - analyze_latent

batch_size: 16

feature_names:
  - diagnosis
  - pantothenate
  - nicotinate
  - taurocholate
  - palmitate
  - s__Coprococcus_comes
  - s__Roseburia_hominis
  - s__Roseburia_intestinalis
  - s__Roseburia_inulinivorans
  - s__Roseburia_unclassified

model:
  num_hidden:
    - 720
  num_latent: 100
  beta: 1e-2

training_loop:
  lr: 1e-4
  num_epochs: 100
  kld_warmup_steps:
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - 23
    - 24
    - 25
