_target_: move.models.vae.VAE

# Use a custom resolver to extract the weights input in 'data/main.yaml'
categorical_names: ${names:${data.categorical_inputs}}
continuous_names: ${names:${data.continuous_inputs}}
categorical_weights: ${weights:${data.categorical_inputs}}
continuous_weights: ${weights:${data.continuous_inputs}}

cuda: False

lr: 0.0001
num_epochs: 4 # for testing
patience: 2 #for testing
repeat: 2
kld_steps:
  - 20
  - 30
  - 40

batch_steps:
  - 50
  - 100
  - 150
  - 200


# num_hidden: 200
# nLantent_04: 200
# num_latent:
#     - 150
#     - 200
#     - 250
#     - 300
# num_layers: 1
# beta: 0.01
# dropout: 0.2
# batch_sizes: 10

# cuda: ${training.cuda}
